# Site settings
theme: jekyll-theme-chirpy 
title: Jindavoll's homepage
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Website used to keep a track of the usefull tools
#baseurl: "/example" # the subpath of your site, e.g. /blog/
url: "http://jindavoll.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  Jindavoll

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
